--- 
abstract: Adds a public, (hopefully) userfriendly bug tracking UI to RT
author: 
  - Thomas Sibley <trs@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.68
license: GPL version 2
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RT-BugTracker-Public
no_index: 
  directory: 
    - etc
    - html
    - inc
    - t
requires: 
  perl: 5.8.3
version: 0.02
